name: Drones build
# on: [push, pull_request]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DRIVER: postgres
      TEST_DRONE_DATABASE: postgresql://postgres:postgres@localhost:5432/drones

    services:
      postgres:
        image: postgres        
        env:
          POSTGRES_DB: drones        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

        ports:
          - 5432:5432

        options: >-
          --name drones_db
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup test database
        run: docker exec drones_db bash -c 'PGPASSWORD=postgres psql -U postgres -d drones -h postgres -p 5432 -a -q -c "CREATE SCHEMA IF NOT EXISTS drones;"'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: | 
          go get ./...
          go install github.com/CloudInn/gorm-goose/cmd/gorm-goose
         

      - name: Run Migrations
        run: gorm-goose -env test -path=repository/db -pgschema=drones up

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
